export const locatorsCheckout = {
    appLogo: '.app_logo',
    title: '.title[data-test="title"]',
    firstNameInput: 'input[data-test="firstName"]',
    lastNameInput: 'input[data-test="lastName"]',
    postalCodeInput: 'input[data-test="postalCode"]',
    cancelButton: 'button[data-test="cancel"]',
    continueButton: 'input[data-test="continue"]',
    badgeElement: '.shopping_cart_badge',
    appLogoText: 'Swag Labs',
    titleText: 'Checkout: Your Information',
    firstNamePlaceholder: 'First Name',
    lastNamePlaceholder: 'Last Name',
    postalCodePlaceholder: 'Zip/Postal Code',
    cancelButtonText: 'Cancel',
    continueButtonText: 'Continue',
    attributePlaceholder: 'placeholder',
    firstNameValue: 'Ash',
    lastNameValue: 'Ketchum',
    postalCodeValue: '12345',
    finishButton: 'button[data-test="finish"]',
    screenshotPath02: 'locators/visualComparisonLocators/02_inventory.png',
    snapshotPath02: 'tests/ui/5_e2e_test/locators-visualComparisonLocators-02-inventory-chromium-darwin.png',
    screenshotPath03: 'locators/visualComparisonLocators/03_addLastElementToCartBasedOnPrice.png',
    snapshotPath03: 'tests/ui/5_e2e_test/locators-visualComparisonLocators-03-addLastElementToCartBasedOnPrice-chromium-darwin.png',
    screenshotPath04: 'locators/visualComparisonLocators/locators-visualComparisonLocators-04-addSecondElementToCartBasedOnAlphabeticalOrder-chromium-darwin.png',
    snapshotPath04: 'tests/ui/5_e2e_test/visualComparisonLocators-04.png'
};